// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCicloContabilDiario.Infrastructure.Persistence;

#nullable disable

namespace SistemaCicloContabilDiario.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241221173500_AddTabelasIniciais")]
    partial class AddTabelasIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaCicloContabilDiario.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransacaoId"));

                    b.Property<int>("CategoriaTransacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdContaDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdContaOrigem")
                        .HasColumnType("int");

                    b.Property<int>("MontanteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransacaoId")
                        .HasColumnType("int");

                    b.HasKey("TransacaoId");

                    b.HasIndex("CategoriaTransacaoId");

                    b.HasIndex("MontanteId");

                    b.HasIndex("TipoTransacaoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("SistemaCicloContabilDiario.Domain.ValueObjects.CategoriaTransacao", b =>
                {
                    b.Property<int>("CategoriaTransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaTransacaoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaTransacaoId");

                    b.ToTable("CategoriasTransacao");
                });

            modelBuilder.Entity("SistemaCicloContabilDiario.Domain.ValueObjects.Montante", b =>
                {
                    b.Property<int>("MontanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MontanteId"));

                    b.Property<decimal>("ValorMontante")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MontanteId");

                    b.ToTable("Montantes");
                });

            modelBuilder.Entity("SistemaCicloContabilDiario.Domain.ValueObjects.TipoTransacao", b =>
                {
                    b.Property<int>("TipoTransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTransacaoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoTransacaoId");

                    b.ToTable("TiposTransacao");
                });

            modelBuilder.Entity("SistemaCicloContabilDiario.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("SistemaCicloContabilDiario.Domain.ValueObjects.CategoriaTransacao", "categoriaTransacao")
                        .WithMany()
                        .HasForeignKey("CategoriaTransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCicloContabilDiario.Domain.ValueObjects.Montante", "Montante")
                        .WithMany()
                        .HasForeignKey("MontanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCicloContabilDiario.Domain.ValueObjects.TipoTransacao", "TipoTransacao")
                        .WithMany()
                        .HasForeignKey("TipoTransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Montante");

                    b.Navigation("TipoTransacao");

                    b.Navigation("categoriaTransacao");
                });
#pragma warning restore 612, 618
        }
    }
}
